setup-dev:
	docker compose -f docker-compose.dev.yaml build --force-rm --no-cache

up-dev:
	docker compose -f docker-compose.dev.yaml up -d

down-dev:
	docker compose -f docker-compose.dev.yaml down

logs-dev:
	docker compose -f docker-compose.dev.yaml logs -f

status-dev:
	docker compose -f docker-compose.dev.yaml ps

setup-prod:
	docker compose -f docker-compose.prod.yaml build --force-rm --no-cache

up-prod:
	docker compose -f docker-compose.prod.yaml up -d

down-prod:
	docker compose -f docker-compose.prod.yaml down

logs-prod:
	docker compose -f docker-compose.prod.yaml logs -f

status-prod:
	docker compose -f docker-compose.prod.yaml ps